name: Katalon Studio Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC (Optional)

jobs:
  run-tests:
    runs-on: windows-latest  # Or macOS-latest if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (Zulu)
        uses: actions/setup-java@v3  # Recommended for Katalon Studio
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Install Katalon Studio (if not pre-installed)
        uses: shinnn/katalon-studio-installer@v1  # Optional, adjust version if needed
        with:
          version: '8.5.5'  # Or your desired version

      - name: Use a specific Katalon Studio version (Optional)
        uses: actions/cache@v3  # Cache Katalon Studio download
        with:
          path: ${{ runner.tempDirectory }}/katalon_studio
          key: ${{ runner.os }}-katalon-${{ env.KATALON_VERSION }}
          restore-keys: |
            ${{ runner.os }}-katalon-

      - name: Download Katalon Studio (if not cached)
        run: |
          if [ ! -f "${{ runner.tempDirectory }}/katalon_studio/katalon.zip" ]; then
            curl -sfL https://download.katalon.com/katalon-studio/katalon-studio-${{ env.KATALON_VERSION }}-windows-64.zip -o "${{ runner.tempDirectory }}/katalon_studio/katalon.zip"
          fi

      - name: Extract Katalon Studio
        run: |
          unzip -qq "${{ runner.tempDirectory }}/katalon_studio/katalon.zip" -d "${{ runner.tempDirectory }}/katalon_studio"

      - name: Set Katalon Studio path
        env:
          KATALON_STUDIO_PATH: ${{ runner.tempDirectory }}/katalon_studio/katalon.exe

      - name: Run Katalon Studio tests
        run: |
          "${{ env.KATALON_STUDIO_PATH }}" -noSplash -retry=0 \
             -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" \
             -apiKey=${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true

      - name: Upload Test Reports (Optional)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: katalon-reports
          path: path/to/your/katalon/reports  # Replace with actual report path
          retention-days: 7

      - name: Clean up (Optional)
        run: echo "Cleaning up..."
