# ... (rest of your workflow YAML)

jobs:
  run-ios-tests:
    runs-on: macos-latest  # macOS runner for iOS testing

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java for Katalon Studio
      - name: Set up Java (Zulu)
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      # Step 3: Run Katalon Studio tests with corrected project path
      - name: Run Katalon Studio tests with Katalon GitHub Action
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '10.0.1'
          projectPath: '${{ github.workspace }}/iOS Mobile Tests with Katalon Studio.prj'  # Assuming the project file is directly under the root directory
          args: '-noSplash -retry=0 \
                 -testSuitePath="Test Suites/IOS_Automation_TestSuite" \
                 -apiKey=${{ secrets.API_KEY }} \
                 --config -mobileDevice=true \
                 -appium:platformName="iOS" \
                 -appium:platformVersion="18.0.1" \
                 -appium:deviceName="iPad" \
                 -appium:bundleId="my.com.etiqa.ease.dev" \
                 -appium:automationName="XCUITest" \
                 -appium:udid="00008020-00180924262A402E"'

      # Optional: Clean up
      - name: Clean up
        run: echo "Cleaning up..."
