name: Run Katalon Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Run Katalon Test Suite
        run: |
          /Applications/Katalon Studio.app/Contents/MacOS/katalon \
          -noSplash -retry=0 \
          -testSuitePath="Test Suites/IOS_Automation_TestSuite" \
          -apiKey=${{ secrets.API_KEY }} \
          --config -mobileDevice=true \
          -appium:platformName="iOS" \
          -appium:platformVersion="18.0.1" \
          -appium:deviceName="iPad" \
          -appium:bundleId="my.com.etiqa.ease.dev" \
          -appium:automationName="XCUITest" \
          -appium:udid="00008020-00180924262A402E"
