name: Katalon Studio Tests

# ... (on section)

jobs:
  run-tests:
    runs-on: windows-latest
    env:
      KATALON_VERSION: '8.6.0' # Set your desired Katalon version here
      KATALON_INSTALL_PATH: C:\katalon # Installation path

    steps:
      # ... (checkout and Java setup)

      - name: Cache Katalon Studio
        id: cache-katalon
        uses: actions/cache@v3
        with:
          path: ${{ env.KATALON_INSTALL_PATH }}
          key: ${{ runner.os }}-katalon-${{ env.KATALON_VERSION }}-${{ hashFiles('**/katalon-studio*.zip') }}
          restore-keys: |
            ${{ runner.os }}-katalon-${{ env.KATALON_VERSION }}-

      - name: Install Katalon Studio (if not cached)
        if: steps.cache-katalon.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://download.katalon.com/katalon-studio/katalon-studio-${{ env.KATALON_VERSION }}-windows-64.zip" -OutFile katalon.zip
          Expand-Archive -Path katalon.zip -DestinationPath ${{ env.KATALON_INSTALL_PATH }}
          Remove-Item katalon.zip

      - name: Run Katalon Studio tests
        shell: pwsh
        run: |
          & "${{ env.KATALON_INSTALL_PATH }}\katalon.exe" -noSplash -runMode=console -projectPath="${{ github.workspace }}" -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey=${{ secrets.API_KEY }} -retry=0 --config -webui.autoUpdateDrivers=true

      # ... (report upload and cleanup)
