name: Run Katalon iOS Tests with Appium

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  run-ios-tests:
    runs-on: macos-latest  # macOS runner for iOS testing

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java for Katalon Studio (using Zulu distribution)
      - name: Set up Java (Zulu)
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version needed for Katalon Studio
          distribution: 'zulu'  # Use Zulu OpenJDK distribution

      # Step 3: Verify files and paths (for debugging)
      - name: List files in repository
        run: |
          ls -la ${{ github.workspace }}  # List files in the workspace to verify file paths

      # Step 4: Run Katalon Studio tests directly using Katalon GitHub Action
      - name: Run Katalon Studio tests with Katalon GitHub Action
        uses: katalon-studio/katalon-studio-github-action@v4.0
        with:
          version: '10.0.1'  # Specify the version of Katalon Studio (adjust this if needed)
          projectPath: '${{ github.workspace }}/iOS Mobile Tests with Katalon Studio.prj'  # Path to your Katalon project
          args: '-noSplash -retry=0 \
                 -testSuitePath="Test Suites/IOS_Automation_TestSuite" \  # Specify the path to your actual test suite
                 -apiKey=${{ secrets.API_KEY }} \
                 --config -mobileDevice=true \
                 -appium:platformName="iOS" \
                 -appium:platformVersion="18.0.1" \
                 -appium:deviceName="iPad" \
                 -appium:bundleId="my.com.etiqa.ease.dev" \
                 -appium:automationName="XCUITest" \
                 -appium:udid="00008020-00180924262A402E" \
                 -licenseRelease=true \
                 -orgID="976796"'\

      # Optional: Clean up
      - name: Clean up
        run: echo "Cleaning up..."
