name: Run Katalon iOS Tests with Appium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-ios-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (Zulu)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Appium dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run Katalon Studio tests
        run: |
          /Applications/Katalon\ Studio.app/Contents/MacOS/katalon \
            -noSplash \
            -retry=0 \
            -testSuitePath="Test Suites/YourTestSuite" \
            -apiKey=${{ secrets.API_KEY }} \
            --config \
            -mobileDevice=true \
            -appium:platformName="iOS" \
            -appium:platformVersion="18.0.1" \
            -appium:deviceName="iPad" \
            -appium:bundleId="my.com.etiqa.ease.dev" \
            -appium:automationName="XCUITest" \
            -appium:udid="00008020-00180924262A402E"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: katalon-reports
          path: ${{ github.workspace }}/Reports
          retention-days: 7
