name: Run Katalon Tests Locally

on:
  workflow_dispatch:  # Manually trigger from GitHub Actions UI

jobs:
  katalon-test:
    runs-on: [self-hosted, macOS, x64]  # Specifies that the job will run on your self-hosted macOS x64 runner

    steps:
      - name: Run Katalon Tests
        run: |
          cd /Users/etiqaqa/Downloads/QAutomation  # Change to your Katalon project directory
          katalon execute -noExit -projectPath=./Katalon_Project.katalon
