name: Run Katalon Studio Tests

on:
  push:
    branches:
      - main

jobs:
  run-katalon-tests:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files in the directory (for debugging)
      run: |
        ls -la ./  # List the files in the root directory of the repo

    - name: Run Katalon Studio tests
      run: |
        katalon-execute -projectPath "./iOS Mobile Tests with Katalon Studio.prj"
