name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest  # Choose the runner for your environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2.1

      # Step 2: Run Katalon Studio tests using the Katalon GitHub Action
      - name: Katalon Studio GitHub Action
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '7.5.5'  # Specify the version of Katalon Studio (adjust based on your requirement)
          projectPath: '${{ github.workspace }}/QAutomation'  # Path to your Katalon project in the repo
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey=${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
        env:
          KATALON_API_KEY: ${{ secrets.API_KEY }}  # Store the API Key in GitHub Secrets
