name: Run Katalon iOS Tests with Appium

on:
  # ... (triggers)

jobs:
  run-ios-tests:
    runs-on: macos-latest
    env:
      KATALON_VERSION: "8.6.0" # Set your desired Katalon version
      KATALON_INSTALL_DIR: ${{ runner.temp }}/katalon

    steps:
      # ... (checkout, Java, Ruby, Appium dependencies - same as Option 1)

      - name: Download Katalon Studio
        run: |
          curl -LO "https://download.katalon.com/katalon-studio/katalon-studio-${{ env.KATALON_VERSION }}-macos.zip"
          unzip katalon-studio-${{ env.KATALON_VERSION }}-macos.zip -d ${{ env.KATALON_INSTALL_DIR }}
          rm katalon-studio-${{ env.KATALON_VERSION }}-macos.zip

      - name: Run Katalon Studio tests
        run: |
          "${{ env.KATALON_INSTALL_DIR }}/Katalon Studio.app/Contents/MacOS/katalon" -noSplash -retry=0 \
            -testSuitePath="Test Suites/YourTestSuite" \
            -apiKey=${{ secrets.API_KEY }} \
            --config -mobileDevice=true \
            -appium:platformName="iOS" \
            -appium:platformVersion="18.0.1" \
            -appium:deviceName="iPad" \
            -appium:bundleId="my.com.etiqa.ease.dev" \
            -appium:automationName="XCUITest" \
            -appium:udid="00008020-00180924262A402E"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: katalon-reports
          path: ${{ github.workspace }}/Reports
          retention-days: 7
