name: Run Katalon Tests Locally

on:
  workflow_dispatch:  # Manually trigger from GitHub Actions UI

jobs:
  katalon-test:
    runs-on: self-hosted  # This will run on your local PC where the self-hosted runner is installed

    steps:
      - name: Run Katalon Tests
        run: |
          cd /Users/etiqaqa/Downloads/QAutomation  # Change to your Katalon project directory
          katalon execute -noExit -projectPath=./Katalon_Project.katalon
