name: Katalon Test Automation

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  schedule:
    - cron: '0 0 * * *'  # Schedule for daily runs at midnight (UTC)

jobs:
  run-katalon-tests:
    runs-on: ubuntu-latest  # Using GitHub-hosted runner with Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checkout code to the runner

      - name: Set up Java
        uses: actions/setup-java@v2  # Set up Java for Katalon execution
        with:
          java-version: '11'  # Set your required Java version

      - name: Install Katalon Studio
        run: |
          wget https://download.katalon.com/ -O katalon.zip  # Adjust URL for correct download link
          unzip katalon.zip -d katalon
          chmod +x katalon/katalon

      - name: Run Katalon Tests
        run: |
          katalon/katalon -noSplash -runMode=console -projectPath=$(pwd)/<path-to-your-project>/KatalonStudio.prj -testSuitePath="Test Suites/YourTestSuite" -browserType="Chrome"

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: katalon-test-results
          path: $(pwd)/<path-to-results-directory>








name: UFT Automation Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *" # Run at 8:00 AM every day (UTC)

jobs:
  run-uft-tests:
    runs-on: windows-latest # UFT requires a Windows environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up dependencies (e.g., UFT runtime engine or tools)
      - name: Set Up UFT Runtime Environment
        run: |
          echo "Setting up UFT dependencies"
          # Add commands to configure UFT if required

      # Step 3: Execute UFT Tests
      - name: Run UFT Tests
        run: |
          echo "Running UFT tests"
          # Replace with the actual command to run your UFT tests
          # Example:
          # "C:\Path\To\UFT\bin\uftbatchrunner.exe" -run -testset <Path-to-TestSet>

      # Step 4: Collect results (optional)
      - name: Collect Test Results
        run: |
          echo "Collecting test results"
          # Add any commands to archive or process results

      # Step 5: Upload Test Results (optional)
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: UFT-Test-Results
          path: <path-to-results>
