name: Run Katalon iOS Tests with Appium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-ios-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Use v3 for better performance and security

      - name: Set up Java (Zulu)
        uses: actions/setup-java@v3 # Use v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Install Ruby and Bundler (for Appium dependencies)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Or a suitable version
          bundler-cache: true # Improves caching for faster runs

      - name: Install Appium dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Katalon Studio tests
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '10.0.1' # Or your desired version
          projectPath: '${{ github.workspace }}/iOS Mobile Tests with Katalon Studio.prj' # Adjust if needed
          args: '-noSplash -retry=0 \
                 -testSuitePath="Test Suites/IOS_Automation_TestSuite" \
                 -apiKey=${{ secrets.API_KEY }} \
                 --config -mobileDevice=true \
                 -appium:platformName="iOS" \
                 -appium:platformVersion="16.0" \ # Use a supported version
                 -appium:deviceName="iPhone 14" \ # Use a valid device name or simulator
                 -appium:bundleId="your.bundle.id" \ # Replace with your actual bundle ID
                 -appium:automationName="XCUITest" \
                 -appium:udid="auto"' # Use 'auto' for simulators or provide a valid UDID

      - name: Upload Test Reports (Optional)
        uses: actions/upload-artifact@v3
        if: always() # Always upload even if tests fail
        with:
          name: katalon-reports
          path: path/to/your/katalon/reports # Replace with the actual path to your reports
          retention-days: 7

      - name: Clean up (Optional)
        run: echo "Cleaning up..."
