name: Run Katalon iOS Tests with Appium

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  run-ios-tests:
    runs-on: macos-latest  # macOS runner for iOS testing

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java for Katalon Studio (using Zulu distribution)
      - name: Set up Java (Zulu)
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version needed for Katalon Studio
          distribution: 'zulu'  # Use Zulu OpenJDK distribution

      # Step 3: Install Katalon Studio
      - name: Install Katalon Studio
        run: |
          wget https://download.katalon.com/10.0.1/Katalon_Studio_Engine_Mac_10.0.1.zip -O katalon.zip  # Adjust for the correct version
          unzip katalon.zip -d katalon
          chmod +x katalon/Katalon_Studio.app/Contents/MacOS/Katalon

      # Step 4: Set up Appium
      - name: Set up Appium
        run: |
          brew install libimobiledevice  # Needed for communicating with iOS devices
          npm install -g appium  # Install Appium globally
          appium driver install uiautomator2 # Install Appium iOS driver for XCUITest

      # Step 5: Run Katalon Tests using Appium capabilities
      - name: Run Katalon Studio iOS tests with Appium
        run: |
          katalon/Katalon_Studio.app/Contents/MacOS/Katalon -noSplash -runMode=console \
          -projectPath=$(pwd)/QAutomation/KatalonStudio.prj \
          -testSuitePath="Test Suites/YourTestSuite" \
          -browserType="Mobile" \
          -deviceName="iPad" \
          -platformVersion="18.0.1" \
          -appium:bundleId="my.com.etiqa.ease.dev" \
          -appium:automationName="XCUITest" \
          -appium:udid="00008020-00180924262A402E" \
          -apiKey=${{ secrets.API_KEY }}  # Pass the Katalon API Key from GitHub Secrets

      # Optional: Step 6: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: katalon-ios-test-results
          path: $(pwd)/QAutomation/Reports  # Ensure reports are saved in the specified directory
