name: Run Katalon iOS Tests

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the master branch
  schedule:
    - cron: '0 0 * * *'  # Optional: Run every day at midnight (UTC)

jobs:
  run-ios-tests:
    runs-on: macos-latest  # macOS runner for iOS tests

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java (required for Katalon)
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Katalon Studio requires Java 11

      # Step 3: Download and Install Katalon Studio
      - name: Install Katalon Studio
        run: |
          wget https://download.katalon.com/10.0.1/Katalon_Studio_Engine_Mac_10.0.1.zip -O katalon.zip
          unzip katalon.zip -d katalon
          chmod +x katalon/Katalon_Studio.app/Contents/MacOS/Katalon

      # Step 4: Run Katalon iOS tests
      - name: Run Katalon iOS Tests
        run: |
          katalon/Katalon_Studio.app/Contents/MacOS/Katalon -noSplash -runMode=console \
          -projectPath=$(pwd)/QAutomation/KatalonStudio.prj \
          -testSuitePath="Test Suites/YourTestSuite" \
          -browserType="Mobile" \
          -deviceName="iPad" \
          -platformVersion="16.0"

      # Optional: Upload test results as artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: katalon-ios-test-results
          path: $(pwd)/QAutomation/Reports  # Ensure the reports are saved in this directory
