name: Run Katalon iOS Tests

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  run-ios-tests:
    runs-on: macos-latest  # macOS runner for iOS tests

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Install Katalon Studio (version 10.0.1)
      - name: Install Katalon Studio 10.0.1
        run: |
          wget https://download.katalon.com/10.0.1/Katalon_Studio_Engine_Mac_10.0.1.zip -O katalon.zip  # Download Katalon 10.0.1 version
          unzip katalon.zip -d katalon  # Unzip the downloaded package
          chmod +x katalon/Katalon_Studio.app/Contents/MacOS/Katalon  # Make Katalon executable

      # Step 3: Run Katalon iOS Tests
      - name: Run iOS Katalon Tests
        run: |
          katalon/Katalon_Studio.app/Contents/MacOS/Katalon -noSplash -runMode=console \
          -projectPath=$(pwd)/QAutomation/KatalonStudio.prj \
          -testSuitePath="Test Suites/New Test Suite" \
          -browserType="Mobile" \
          -deviceName="AT ipad" \
          -platformVersion="18.0.1"  # Ensure these match your iOS device configurations

      # Optional: Step 4: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: katalon-ios-test-results
          path: $(pwd)/QAutomation/Reports  # Path to the reports generated by Katalon Studio
