name: Run Katalon iOS Tests

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  schedule:
    - cron: '0 0 * * *'  # Schedule to run daily at midnight UTC

jobs:
  run-ios-tests:
    runs-on: macos-latest  # macOS runner for iOS tests

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Java (required for Katalon Studio)
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Install Katalon Studio (latest stable version)
      - name: Install Katalon Studio
        run: |
          wget https://download.katalon.com/7.9.1/Katalon_Studio_Engine_Mac_7.9.1.zip -O katalon.zip
          unzip katalon.zip -d katalon
          chmod +x katalon/Katalon_Studio.app/Contents/MacOS/Katalon

      # Step 4: Run Katalon Tests
      - name: Run iOS Katalon Tests
        run: |
          katalon/Katalon_Studio.app/Contents/MacOS/Katalon -noSplash -runMode=console \
          -projectPath=$(pwd)/QAutomation/KatalonStudio.prj \
          -testSuitePath="Test Suites/New Test Suite" \
          -browserType="Mobile" \
          -deviceName="AT ipad" \
          -platformVersion="18.0.1"
