name: Run Katalon iOS Tests

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  run-ios-tests:
    runs-on: macos-latest  # macOS runner for iOS tests

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Java (Katalon requires Java to run)
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Set the Java version to 11 for Katalon Studio

      # Step 3: Install Katalon Studio (latest stable version)
      - name: Install Katalon Studio
        run: |
          wget https://download.katalon.com/7.9.1/Katalon_Studio_Engine_Mac_7.9.1.zip -O katalon.zip  # Download Katalon Studio
          unzip katalon.zip -d katalon  # Unzip the downloaded package
          chmod +x katalon/Katalon_Studio.app/Contents/MacOS/Katalon  # Make Katalon executable

      # Step 4: Run Katalon iOS Tests
      - name: Run iOS Katalon Tests
        run: |
          katalon/Katalon_Studio.app/Contents/MacOS/Katalon -noSplash -runMode=console \
          -projectPath=$(pwd)/QAutomation/KatalonStudio.prj \
          -testSuitePath="Test Suites/New Test Suite" \
          -browserType="Mobile" \
          -deviceName="AT ipad" \
          -platformVersion="18.0.1"  # Update to match the iOS device you are testing with

      # Optional: Step 5: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: katalon-ios-test-results
          path: $(pwd)/QAutomation/Reports  # Path to the reports generated by Katalon Studio
